### ISSUE TITLE
Missing "amplify_outputs.json" File in Project

### ISSUE THREAD

**Issue by aditya28n99** [svb-hikip/hikipfe-react#1]
Hi,
I have cloned the repository and installed the dependencies further started dev server. However, when I try to ran the url " http://localhost:5173", I encounter the following error:

"[plugin:vite:import-analysis] Failed to resolve import "../amplify_outputs.json" from "src/App.jsx". Does the file exist?"

It appears like the "amplify_outputs.json" file is missing from the project directory. Could you please provide me some guidance on how to obtain or generate this file?

regards,
Aditya Wakale (Jain)

**Comment by svb-hikip** [comment]
have added this file, Please try now

**Comment by svb-hikip** [comment]
I have added the file in the repository, please try now
