### ISSUE TITLE
Added Suspense and Loader for Loading Client List

### ISSUE THREAD

**Issue by aditya28n99** [svb-hikip/hikipfe-react#15]
When the client list is being loaded on the /dashboard/clients page, a suspense component should be added to enhance the user experience by displaying a loading indicator.

Proposed Solution:
1. Identified where the client list data is being fetched in the code.
2. Wrapped the client list component with React.Suspense.
3. Created a simple loading component.
4. Tested the implementation to ensure that the loading component appears while the data is being fetched and disappears once the data is loaded.

**Comment by svb-hikip** [comment]
Good Idea!

**Comment by svb-hikip** [comment]
This is already done by @anthonym995 ? Can you comment?
