### ISSUE TITLE
File Missing "amplify_outputs.json"

### ISSUE THREAD

**Issue by anthonym995** [svb-hikip/hikipfe-react#2]
### Description

Missing **"output"** folder and **"amplify_outputs.json"** file, Failed to resolve import "../amplify_outputs.json" from "src/App.jsx" while run dev server

### Screenshots

![amplify](https://github.com/svb-hikip/hikipfe-react/assets/78245507/5737bf5b-182a-49e7-990e-73f50d0c0da0)

**Comment by svb-hikip** [comment]
have added this file, Please try now
