### ISSUE TITLE
Task 1 - Client Search bar

### ISSUE THREAD

**Issue by svb-hikip** [svb-hikip/hikipfe-react#27]
![image](https://github.com/svb-hikip/hikipfe-react/assets/172111960/4478265d-f838-485d-813b-c24baffe6d00)

When a user searches a client name in the top search bar, it should start filtering. 

Use HeadlessUI for this task.
Use https://tailwindui.com/ If you need login credentials, telegram me. 

I will give you api endpoint for this after this task is assigned to someone.

**Comment by svb-hikip** [comment]
Please take note that the search bar will be used from anywhere, for example when I use it from bills list page, it should work. Maybe use a layover or a modal or however you feel is the best option.

**Comment by anthonym995** [comment]
can we implement the search bar in individual component itself ?

**Comment by svb-hikip** [comment]
@anthonym995 You can take whichever approach you like, it should be elegant!

**Comment by svb-hikip** [comment]
I got the API ready. Pull the new changes before you proceed.

API ENDPOINTS AND DOCS
https://hikip-django-e06ccc5f06d1.herokuapp.com/api/schema/swagger-ui/

https://hikip-django-e06ccc5f06d1.herokuapp.com/api/schema/redoc/
