### ISSUE TITLE
Task 2 - Appointment Delete option

### ISSUE THREAD

**Issue by svb-hikip** [svb-hikip/hikipfe-react#28]
![image](https://github.com/svb-hikip/hikipfe-react/assets/172111960/6e3a1c51-7b3d-4bf2-a5f7-77636b4e25fd)

The Appointment delete option should be working. 

I will give you delete API endpoint when this task is assigned to someone

**Comment by anthonym995** [comment]
Let me work on this issue #28

**Comment by anthonym995** [comment]
Please provide me the delete API endpoint

**Comment by anthonym995** [comment]
Please update the delete API endpoint

**Comment by svb-hikip** [comment]
I got the API ready. Pull the new changes before you proceed.

API ENDPOINTS AND DOCS
https://hikip-django-e06ccc5f06d1.herokuapp.com/api/schema/swagger-ui/

https://hikip-django-e06ccc5f06d1.herokuapp.com/api/schema/redoc/

**Comment by svb-hikip** [comment]
Completed by @anthonym995
