### ISSUE TITLE
Task 3 - Bills more details and delete

### ISSUE THREAD

**Issue by svb-hikip** [svb-hikip/hikipfe-react#29]
![image](https://github.com/svb-hikip/hikipfe-react/assets/172111960/feb0068d-afac-4370-a6ba-b7c71575c664)

The options should be changed to More Details and Delete when I click the three point icon on the right end. 

More details and delete option should work! more details should take me to the invoice page

I will give you API endpoint when this task is assigned

**Comment by Edukondalu71** [comment]
can your share api end point

**Comment by svb-hikip** [comment]
I got the API ready. Pull the new changes before you proceed.

API ENDPOINTS AND DOCS
https://hikip-django-e06ccc5f06d1.herokuapp.com/api/schema/swagger-ui/

https://hikip-django-e06ccc5f06d1.herokuapp.com/api/schema/redoc/

**Comment by aditya28n99** [comment]
Thank you for your feedback and for merging my previous contributions. I have pulled the latest changes and reviewed the new API documentation.

I will proceed with Task 3, which includes:

1. Changing the options to "More Details" and "Delete" in the Bills component.
2.. Implementing the functionality for "More Details" to navigate to the invoice page.
3. Implementing the delete functionality to remove the bill entry.

I will keep you updated on the progress. Please let me know if you have any additional instructions or considerations.

**Comment by svb-hikip** [comment]
The Bill Component has changed. Please check new commits.

**Comment by aditya28n99** [comment]
After pulling the latest changes and running the development server, I encountered an issue with missing dependencies, specifically react-toastify. The error message is as follows:

Error: The following dependencies are imported but could not be resolved:

  react-toastify (imported by D:/WEB Programing/React Projects/Hiki App/hikipfe-react/src/apis/BaseAPI.js)
  react-toastify/dist/ReactToastify.css (imported by D:/WEB Programing/React Projects/Hiki App/hikipfe-react/src/App.jsx)
Are they installed?
Please provide some guidence.. should i install those?
![image](https://github.com/svb-hikip/hikipfe-react/assets/125676395/b5c959fa-df40-4164-b79c-859eec902dc8)

**Comment by aditya28n99** [comment]
I have pulled the latest changes and noticed that the Bill Component and the overall UI have changed significantly. to work with the task, could you please provide more details about the updates and any specific requirements or changes you have in mind?

**Comment by svb-hikip** [comment]
Yes this task is now redundant! Shall I close it?

**Comment by aditya28n99** [comment]
sure!!

**Comment by svb-hikip** [comment]
@aditya28n99  Please takeup Task 5 - Invoice page
