### ISSUE TITLE
Task 8 - Upload file, Delete file and Display files (Mockup only)

### ISSUE THREAD

**Issue by svb-hikip** [svb-hikip/hikipfe-react#34]
![image](https://github.com/svb-hikip/hikipfe-react/assets/172111960/5876ee76-8ae9-4602-bfe9-e90664477a42)

Make a mock up with dummy data, a client file list display with add files and delete files.

We shall make it operational after I get the backend ready for file upload.

**Comment by aditya28n99** [comment]
Updated Files component to include file upload, displying files and deleting files functionality. please review the pull request.

**Comment by svb-hikip** [comment]
Completed by @aditya28n99
