### ISSUE TITLE
Task 9 - Client details improvement

### ISSUE THREAD

**Issue by svb-hikip** [svb-hikip/hikipfe-react#35]
![image](https://github.com/svb-hikip/hikipfe-react/assets/172111960/bceb102c-2f74-4777-bb72-e897753250bf)

The client details need a bit of attention, use heroicons/react wherever required

check what all data the API is fetching and Add more client data to the details page 

Use only Tailwind css and Tailwind UI for beautification

**Comment by aditya28n99** [comment]
I'd like to contributing to Task 9 - Client details improvement #35. Building on the client list page, I believe I can make valuable enhancements to the client details page. I'll focus on utilizing Tailwind CSS and Tailwind UI to ensure a polished and cohesive design. Additionally, I'll carefully review the API data to identify opportunities for enriching the client details with more relevant information. please let me know if you have any additional requirements or suggestions for this task.

**Comment by svb-hikip** [comment]
@aditya28n99  Please go ahead, let me know if you need anything

**Comment by aditya28n99** [comment]
I've updated the ClientDetails component as per the instructions. The component now fetches additional client data from the API and displays it on the details page.

Regarding the additional part "type": "Mobile", "voice": true, "text": true, should we include this in the client details? Please advise.

Attached is a screenshot of the current UI for your reference. Please review and let me know if any further adjustments are needed.

![image](https://github.com/svb-hikip/hikipfe-react/assets/125676395/6e72bb83-519a-4e2a-a290-42d43e029095)

**Comment by svb-hikip** [comment]
@aditya28n99 Very nice !! Good job Looks amazing

Please check if it is compatible with new api. Let me know if any changes in API you suggest.

I got the API ready. Pull the new changes before you proceed.

API ENDPOINTS AND DOCS
https://hikip-django-e06ccc5f06d1.herokuapp.com/api/schema/swagger-ui/

https://hikip-django-e06ccc5f06d1.herokuapp.com/api/schema/redoc/

**Comment by svb-hikip** [comment]
completed by @aditya28n99
