### ISSUE TITLE
Task 10 - Beautify the Client list

### ISSUE THREAD

**Issue by svb-hikip** [svb-hikip/hikipfe-react#36]
![image](https://github.com/svb-hikip/hikipfe-react/assets/172111960/ea33db36-8fb0-4d60-b480-b040b7e9838f)

This client list is so bland, add heroicons/react icons, use Tailwind CSS and Tailwind UI to beautify

Check what all data the API fetches and decide if any more details need to be added to this list.

**Comment by aditya28n99** [comment]
I have reviewed the requirements for beautifying the client list and have already started implementing the necessary changes. Here's an overview of my approach and the steps I've taken so far:

- Applied Tailwind CSS classes to style the client list, ensuring a clean and modern design. This includes styling for profile images, client names, emails, roles, and last seen status.

Next Steps: Continue refining the UI, possibly adding more details.

pls let me know if you have any additional requirements or suggestions for this task.

**Comment by svb-hikip** [comment]
You can use pills and badges wherever required!

**Comment by aditya28n99** [comment]
Thank you for the suggestion to use pills and badges. I've updated the ClientListStack component to incorporate these elements for better visual distinction and information clarity. Specifically, I added:

Pills for displaying client types.
Badges for highlighting client relationships.
These additions should improve the UI by making key information more prominent and easily identifiable. Please review the changes and let me know if any further adjustments are needed.

**Comment by aditya28n99** [comment]
![image](https://github.com/svb-hikip/hikipfe-react/assets/125676395/aaf94cc6-1597-4a4c-a80e-87454b7c225e)

**Comment by svb-hikip** [comment]
@aditya28n99 Very Nice!!!!!!!

I got the API ready. Pull the new changes before you proceed.

API ENDPOINTS AND DOCS
https://hikip-django-e06ccc5f06d1.herokuapp.com/api/schema/swagger-ui/

https://hikip-django-e06ccc5f06d1.herokuapp.com/api/schema/redoc/

**Comment by svb-hikip** [comment]
Completed by @aditya28n99
