### ISSUE TITLE
Task-12 ,Billing Component Showing JSON Data and  Billing Details Componet showing Doubled Header .

### ISSUE THREAD

**Issue by me-neeraj135** [svb-hikip/hikipfe-react#42]
#### Description
The Billing component is experiencing two main issues:
1. JSON data is being displayed directly in the UI.
2. The header is appearing twice.

#### Actual Behavior
- Raw JSON data is being shown on the screen.
- There are two headers displayed instead of one.

#### Expected Behavior
- The UI should display the billing information in a readable format.
- The header should appear only once.

#### Screenshots

[![Screenshot-from-2024-06-11-16-47-22.png](https://i.postimg.cc/LXvMCy7f/Screenshot-from-2024-06-11-16-47-22.png)](https://postimg.cc/KkKV45mv)
[![Screenshot-from-2024-06-11-16-48-22.png](https://i.postimg.cc/wjP5JgjR/Screenshot-from-2024-06-11-16-48-22.png)](https://postimg.cc/4Y6hRCtX)

**Comment by me-neeraj135** [comment]
Please assign this issue to me @svb0866

**Comment by svb-hikip** [comment]
@me-neeraj135  Please go ahead

I got the API ready. Pull the new changes before you proceed.

API ENDPOINTS AND DOCS
https://hikip-django-e06ccc5f06d1.herokuapp.com/api/schema/swagger-ui/

https://hikip-django-e06ccc5f06d1.herokuapp.com/api/schema/redoc/

**Comment by svb-hikip** [comment]
Closing, already fixed.
