### ISSUE TITLE
Appointments & Billings Data's aren't fetching properly.

### ISSUE THREAD

**Issue by Kiruba2602** [svb-hikip/hikipfe-react#43]
![Screenshot 2024-06-11 185132](https://github.com/svb-hikip/hikipfe-react/assets/139777602/d7d4fb93-e59a-4945-9c19-397151674b6a)
![Screenshot 2024-06-11 185056](https://github.com/svb-hikip/hikipfe-react/assets/139777602/72c6e381-aa55-4490-ac3a-1d1865f1a725)

**Comment by svb-hikip** [comment]
Hey @Kiruba2602 I was on a 10 hour API coding marathon getting the API ready. Pull the new changes before you proceed.

API ENDPOINTS AND DOCS
https://hikip-django-e06ccc5f06d1.herokuapp.com/api/schema/swagger-ui/

https://hikip-django-e06ccc5f06d1.herokuapp.com/api/schema/redoc/

**Comment by svb-hikip** [comment]
Hopefully working after new commits. reopen if you still face this issue
