### ISSUE TITLE
Client List is not visible

### ISSUE THREAD

**Issue by AchalSPatil** [svb-hikip/hikipfe-react#48]
I am unable to see Client list after login
![image](https://github.com/svb-hikip/hikipfe-react/assets/120000810/566fcd69-f7c9-4ad1-8894-2d4957d33e22)
![image](https://github.com/svb-hikip/hikipfe-react/assets/120000810/406f56e1-afb9-448f-80f2-59518e2ee353)

**Comment by svb-hikip** [comment]
Not able to replicate this issue, reopen if you face it again
