### ISSUE TITLE
Not able to fetch clients

### ISSUE THREAD

**Issue by vaibhav-chittora** [svb-hikip/hikipfe-react#49]
When we click on a particular client - it is showing this error.
![Screenshot 2024-06-12 135908](https://github.com/svb-hikip/hikipfe-react/assets/91217124/7321824c-114a-4476-8ea4-a5a7882e8def)

**Comment by svb-hikip** [comment]
Please check if you have downloaded the latest commits. Please check console log if any errors are printed

**Comment by vaibhav-chittora** [comment]
I have synced my fork repo with the latest commits also, but still the issue is coming

**Comment by svb0866** [comment]
Please check console log if any errors are printed

**Comment by svb-hikip** [comment]
Not able to replicate this issue, reopen if you face it again
