### ISSUE TITLE
No Data in Appointments & Bills tab in Clients

### ISSUE THREAD

**Issue by Kiruba2602** [svb-hikip/hikipfe-react#53]
![Screenshot 2024-06-12 173408](https://github.com/svb-hikip/hikipfe-react/assets/139777602/9bff939b-a2e4-42a0-b25e-9bdbf2070f09)
![Screenshot 2024-06-12 173316](https://github.com/svb-hikip/hikipfe-react/assets/139777602/e7148d7e-15fb-4dc1-b12f-cc1c6102d7e6)

**Comment by svb-hikip** [comment]
Dear @Kiruba2602 Can you refresh, Also check the console log if the API calls have failed. The API calls are very slow, that could be the reason. I will improve the API performance meanwhile.

**Comment by svb-hikip** [comment]
Maybe this client had no appointments and bills. I have made a few changes to display no data message.
