### ISSUE TITLE
localhost:5173/  this Failed to resolve import

### ISSUE THREAD

**Issue by anthonym995** [svb-hikip/hikipfe-react#55]
### Description 

while run the server with __localhost:5173/__ it throws error
Due to there is no redirect done in the router configuration.
 **"/"** redirected to **" /dashboard"** 

### Screenshot
![localhost](https://github.com/svb-hikip/hikipfe-react/assets/78245507/ab27e4ca-ab0c-4742-b875-e96ffd1bffde)

**Comment by svb-hikip** [comment]
Did you run npm install after pulling changes?

**Comment by svb-hikip** [comment]
Please reopen if not fixed after running npm install

**Comment by anthonym995** [comment]
Sure will update soon.

**Comment by anthonym995** [comment]
localhost:5173/ this Failed to resolve import works fine
