### ISSUE TITLE
Access denied to push branches

### ISSUE THREAD

**Issue by anthonym995** [svb-hikip/hikipfe-react#6]
### Description
I was unable push branches to remote repo shows access denied, please provide access.

### Screenshots
![git_access](https://github.com/svb-hikip/hikipfe-react/assets/78245507/86e39849-766b-4719-b5ad-10ae25100fb7)

**Comment by svb-hikip** [comment]
Do not push to origin, Create a separate branch for yourself and then push the branch. If everything is fine and the code is acceptable, we will merge the branch

**Comment by svb-hikip** [comment]
Let me know if it is working

**Comment by svb-hikip** [comment]
To contribute to a public repository you will have to fork that repository, creating your version which you will have write access to, write to that version, and then send a pull request from that version back to the original repository.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by svb-hikip** [comment]
![image](https://github.com/svb-hikip/hikipfe-react/assets/172111960/3544ba27-d4d6-4a09-8701-7f04a24c1867)


After you make the changes in your forked repo, you will get an button for contribute Check the screenshot of a forked repo above
