### ISSUE TITLE
#Issue - AppointmentCalendarDetail

### ISSUE THREAD

**Issue by Kiruba2602** [svb-hikip/hikipfe-react#62]
Hi, @svb-hikip  Can you pls check AppointmentCalendarDetail component. The Client name, Items names, services name are displaying properly.

![Screenshot 2024-06-14 103839](https://github.com/svb-hikip/hikipfe-react/assets/139777602/376db8ca-e5e1-4306-987f-c00e0bb329eb)
![Screenshot 2024-06-14 103927](https://github.com/svb-hikip/hikipfe-react/assets/139777602/1b3ff65a-4af2-427a-b609-68bb26a27b51)

**Comment by Kiruba2602** [comment]
Guys, @anthonym995 and @aditya28n99 if you notify any mistake and changes to be done pls go ahead with this issue.

**Comment by anthonym995** [comment]
sure will update

**Comment by Kiruba2602** [comment]
Guys, @anthonym995 @aditya28n99 I forgot to update the appointmentcalendardetail component in repository and just now added the changes I have done. Please the pull the changes and continue your work.

**Comment by aditya28n99** [comment]
Thanks, Pulled the latest changes. Appreciate the heads-up!
